name: Continuous Deployment

# Only build when pushing to master.
on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Publish to GitHub Pages

    # Use Ubuntu.
    runs-on: ubuntu-latest

    steps:
      # Check out the repository.
      - name: Check Out
        uses: actions/checkout@v2

      # Set up node.
      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Install dependencies.
      - name: Install Dependencies
        run: npm ci

      # Publish documentation to GitHub Pages.
      - name: Generate Docs
        run: npm run build:docs

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/

  npm:
    name: Publish to NPM

    # Use Ubuntu.
    runs-on: ubuntu-latest

    steps:
      # Check out the repository.
      - name: Check Out
        uses: actions/checkout@v2

      # Set up node.
      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Build the project.
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build

      # Publish to NPM
      - name: Publish
        run: .github/scripts/publish-to-npm.sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}