name: Continuous Integration

# Run for all commits not in master.
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Tests

    # Use Ubuntu.
    runs-on: ubuntu-latest

    steps:
      # Check out the repository.
      - name: Check Out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Set up node.
      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Test the project.
      - name: Install Dependencies
        run: npm ci
      - name: Unit Test
        run: npm run test:ci

      # Run analysis.
      - name: Static Analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
