name: Publish documentation to GitHub Pages

# Only build when pushing to master.
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish

    # Use Ubuntu.
    runs-on: ubuntu-latest

    steps:
      # Check out the repository.
      - uses: actions/checkout@v2

      # Set up node.
      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Install dependencies.
      - run: npm ci

      # Publish documentation to GitHub Pages.
      - run: npm run build:docs
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/
