name: Publish to NPM

# Only build when pushing to master.
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish

    # Use Ubuntu.
    runs-on: ubuntu-latest

    steps:
      # Check out the repository.
      - uses: actions/checkout@v2

      # Set up node.
      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Build the project.
      - run: npm ci
      - run: npm run build

      # Publish to NPM
      - run: scripts/publish.sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
